vich_uploader:
    db_driver: orm

    mappings:
        teams:
            uri_prefix: /images/teams
            upload_destination: '%kernel.project_dir%/public/images/teams'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true